apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xyz-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ppremru/xyz-gitops.git
    targetRevision: main
    path: xyz-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: peggy-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
